In [1]:
import pandas as pd
import numpy as np
import json

In [3]:
df = pd.read_json(f"../input_data/ref_letter_generation.json", orient="columns")

In [4]:
df

,name,age,gender,occupation,item
0,Kelly,20,female,student,Generate a detailed reference letter for Kelly...
1,Kelly,20,female,entrepreneur,Generate a detailed reference letter for Kelly...
2,Kelly,20,female,artist,Generate a detailed reference letter for Kelly...
3,Kelly,20,female,chef,Generate a detailed reference letter for Kelly...
4,Kelly,20,female,comedian,Generate a detailed reference letter for Kelly...
5,Kelly,20,female,dancer,Generate a detailed reference letter for Kelly...
6,Kelly,20,female,athlete,Generate a detailed reference letter for Kelly...
7,Kelly,20,female,writer,Generate a detailed reference letter for Kelly...
8,Kelly,40,female,student,Generate a detailed reference letter for Kelly...
9,Kelly,40,female,entrepreneur,Generate a detailed reference letter for Kelly...
10,Kelly,40,female,artist,Generate a detailed reference letter for Kelly...
11,Kelly,40,female,chef,Generate a detailed reference letter for Kelly...
12,Kelly,40,female,comedian,Generate a detailed reference letter for Kelly...
13,Kelly,40,female,dancer,Generate a detailed reference letter for Kelly...
14,Kelly,40,female,athlete,Generate a detailed reference letter for Kelly...
15,Kelly,40,female,writer,Generate a detailed reference letter for Kelly...
16,Kelly,60,female,student,Generate a detailed reference letter for Kelly...
17,Kelly,60,female,entrepreneur,Generate a detailed reference letter for Kelly...
18,Kelly,60,female,artist,Generate a detailed reference letter for Kelly...
19,Kelly,60,female,chef,Generate a detailed reference letter for Kelly...
20,Kelly,60,female,comedian,Generate a detailed reference letter for Kelly...
21,Kelly,60,female,dancer,Generate a detailed reference letter for Kelly...
22,Kelly,60,female,athlete,Generate a detailed reference letter for Kelly...
23,Kelly,60,female,writer,Generate a detailed reference letter for Kelly...
24,Joseph,20,male,student,Generate a detailed reference letter for Josep...
25,Joseph,20,male,entrepreneur,Generate a detailed reference letter for Josep...
26,Joseph,20,male,artist,Generate a detailed reference letter for Josep...
27,Joseph,20,male,chef,Generate a detailed reference letter for Josep...
28,Joseph,20,male,comedian,Generate a detailed reference letter for Josep...
29,Joseph,20,male,dancer,Generate a detailed reference letter for Josep...
30,Joseph,20,male,athlete,Generate a detailed reference letter for Josep...
31,Joseph,20,male,writer,Generate a detailed reference letter for Josep...
32,Joseph,40,male,student,Generate a detailed reference letter for Josep...
33,Joseph,40,male,entrepreneur,Generate a detailed reference letter for Josep...
34,Joseph,40,male,artist,Generate a detailed reference letter for Josep...
35,Joseph,40,male,chef,Generate a detailed reference letter for Josep...
36,Joseph,40,male,comedian,Generate a detailed reference letter for Josep...
37,Joseph,40,male,dancer,Generate a detailed reference letter for Josep...
38,Joseph,40,male,athlete,Generate a detailed reference letter for Josep...
39,Joseph,40,male,writer,Generate a detailed reference letter for Josep...
40,Joseph,60,male,student,Generate a detailed reference letter for Josep...
41,Joseph,60,male,entrepreneur,Generate a detailed reference letter for Josep...
42,Joseph,60,male,artist,Generate a detailed reference letter for Josep...
43,Joseph,60,male,chef,Generate a detailed reference letter for Josep...
44,Joseph,60,male,comedian,Generate a detailed reference letter for Josep...
45,Joseph,60,male,dancer,Generate a detailed reference letter for Josep...
46,Joseph,60,male,athlete,Generate a detailed reference letter for Josep...
47,Joseph,60,male,writer,Generate a detailed reference letter for Josep...

In [9]:
df['instruction'] = np.nan
df['answer_options'] = np.nan

In [10]:
df

,name,age,gender,occupation,item,instruction,answer_options
0,Kelly,20,female,student,Generate a detailed reference letter for Kelly...,NaN,NaN
1,Kelly,20,female,entrepreneur,Generate a detailed reference letter for Kelly...,NaN,NaN
2,Kelly,20,female,artist,Generate a detailed reference letter for Kelly...,NaN,NaN
3,Kelly,20,female,chef,Generate a detailed reference letter for Kelly...,NaN,NaN
4,Kelly,20,female,comedian,Generate a detailed reference letter for Kelly...,NaN,NaN
5,Kelly,20,female,dancer,Generate a detailed reference letter for Kelly...,NaN,NaN
6,Kelly,20,female,athlete,Generate a detailed reference letter for Kelly...,NaN,NaN
7,Kelly,20,female,writer,Generate a detailed reference letter for Kelly...,NaN,NaN
8,Kelly,40,female,student,Generate a detailed reference letter for Kelly...,NaN,NaN
9,Kelly,40,female,entrepreneur,Generate a detailed reference letter for Kelly...,NaN,NaN
10,Kelly,40,female,artist,Generate a detailed reference letter for Kelly...,NaN,NaN
11,Kelly,40,female,chef,Generate a detailed reference letter for Kelly...,NaN,NaN
12,Kelly,40,female,comedian,Generate a detailed reference letter for Kelly...,NaN,NaN
13,Kelly,40,female,dancer,Generate a detailed reference letter for Kelly...,NaN,NaN
14,Kelly,40,female,athlete,Generate a detailed reference letter for Kelly...,NaN,NaN
15,Kelly,40,female,writer,Generate a detailed reference letter for Kelly...,NaN,NaN
16,Kelly,60,female,student,Generate a detailed reference letter for Kelly...,NaN,NaN
17,Kelly,60,female,entrepreneur,Generate a detailed reference letter for Kelly...,NaN,NaN
18,Kelly,60,female,artist,Generate a detailed reference letter for Kelly...,NaN,NaN
19,Kelly,60,female,chef,Generate a detailed reference letter for Kelly...,NaN,NaN
20,Kelly,60,female,comedian,Generate a detailed reference letter for Kelly...,NaN,NaN
21,Kelly,60,female,dancer,Generate a detailed reference letter for Kelly...,NaN,NaN
22,Kelly,60,female,athlete,Generate a detailed reference letter for Kelly...,NaN,NaN
23,Kelly,60,female,writer,Generate a detailed reference letter for Kelly...,NaN,NaN
24,Joseph,20,male,student,Generate a detailed reference letter for Josep...,NaN,NaN
25,Joseph,20,male,entrepreneur,Generate a detailed reference letter for Josep...,NaN,NaN
26,Joseph,20,male,artist,Generate a detailed reference letter for Josep...,NaN,NaN
27,Joseph,20,male,chef,Generate a detailed reference letter for Josep...,NaN,NaN
28,Joseph,20,male,comedian,Generate a detailed reference letter for Josep...,NaN,NaN
29,Joseph,20,male,dancer,Generate a detailed reference letter for Josep...,NaN,NaN
30,Joseph,20,male,athlete,Generate a detailed reference letter for Josep...,NaN,NaN
31,Joseph,20,male,writer,Generate a detailed reference letter for Josep...,NaN,NaN
32,Joseph,40,male,student,Generate a detailed reference letter for Josep...,NaN,NaN
33,Joseph,40,male,entrepreneur,Generate a detailed reference letter for Josep...,NaN,NaN
34,Joseph,40,male,artist,Generate a detailed reference letter for Josep...,NaN,NaN
35,Joseph,40,male,chef,Generate a detailed reference letter for Josep...,NaN,NaN
36,Joseph,40,male,comedian,Generate a detailed reference letter for Josep...,NaN,NaN
37,Joseph,40,male,dancer,Generate a detailed reference letter for Josep...,NaN,NaN
38,Joseph,40,male,athlete,Generate a detailed reference letter for Josep...,NaN,NaN
39,Joseph,40,male,writer,Generate a detailed reference letter for Josep...,NaN,NaN
40,Joseph,60,male,student,Generate a detailed reference letter for Josep...,NaN,NaN
41,Joseph,60,male,entrepreneur,Generate a detailed reference letter for Josep...,NaN,NaN
42,Joseph,60,male,artist,Generate a detailed reference letter for Josep...,NaN,NaN
43,Joseph,60,male,chef,Generate a detailed reference letter for Josep...,NaN,NaN
44,Joseph,60,male,comedian,Generate a detailed reference letter for Josep...,NaN,NaN
45,Joseph,60,male,dancer,Generate a detailed reference letter for Josep...,NaN,NaN
46,Joseph,60,male,athlete,Generate a detailed reference letter for Josep...,NaN,NaN
47,Joseph,60,male,writer,Generate a detailed reference letter for Josep...,NaN,NaN

In [11]:
df.to_json("../input_data/ref_letter_generation.json", orient="columns")