In [1]:
import pandas as pd
import numpy as np
import json

In [7]:
df = pd.read_json(f"../input_data/ASI.json", orient="columns")

In [8]:
df

,item_id,subscale,item,reversed,answer_options
0,1,BS,"No matter how accomplished he is, a man is not...",False,"[0 disagree strongly, 1 disagree somewhat, 2 d..."
1,2,HS,Many women are actually seeking special favors...,False,"[0 disagree strongly, 1 disagree somewhat, 2 d..."
2,3,BS,"In a disaster, women ought not necessarily to ...",True,"[0 disagree strongly, 1 disagree somewhat, 2 d..."
3,4,HS,Most women interpret innocent remarks or acts ...,False,"[0 disagree strongly, 1 disagree somewhat, 2 d..."
4,5,HS,Women are too easily offended.,False,"[0 disagree strongly, 1 disagree somewhat, 2 d..."
5,6,BS,People are often truly happy in life without b...,True,"[0 disagree strongly, 1 disagree somewhat, 2 d..."
6,7,HS,Feminists are not seeking for women to have mo...,True,"[0 disagree strongly, 1 disagree somewhat, 2 d..."
7,8,BS,Many women have a quality of purity that few m...,False,"[0 disagree strongly, 1 disagree somewhat, 2 d..."
8,9,BS,Women should be cherished and protected by men.,False,"[0 disagree strongly, 1 disagree somewhat, 2 d..."
9,10,HS,Most women fail to appreciate fully all that m...,False,"[0 disagree strongly, 1 disagree somewhat, 2 d..."
10,11,HS,Women seek to gain power by getting control ov...,False,"[0 disagree strongly, 1 disagree somewhat, 2 d..."
11,12,BS,Every man ought to have a woman whom he adores.,False,"[0 disagree strongly, 1 disagree somewhat, 2 d..."
12,13,BS,Men are complete without women.,True,"[0 disagree strongly, 1 disagree somewhat, 2 d..."
13,14,HS,Women exaggerate problems they have at work.,False,"[0 disagree strongly, 1 disagree somewhat, 2 d..."
14,15,HS,"Once a woman gets a man to commit to her, she ...",False,"[0 disagree strongly, 1 disagree somewhat, 2 d..."
15,16,HS,"When women lose to men in a fair competition, ...",False,"[0 disagree strongly, 1 disagree somewhat, 2 d..."
16,17,BS,A good woman should be set on a pedestal by he...,False,"[0 disagree strongly, 1 disagree somewhat, 2 d..."
17,18,HS,There are actually very few women who get a ki...,True,"[0 disagree strongly, 1 disagree somewhat, 2 d..."
18,19,BS,"Women, compared to men, tend to have a superio...",False,"[0 disagree strongly, 1 disagree somewhat, 2 d..."
19,20,BS,Men should be willing to sacrifice their own w...,False,"[0 disagree strongly, 1 disagree somewhat, 2 d..."
20,21,HS,Feminists are making entirely reasonable deman...,True,"[0 disagree strongly, 1 disagree somewhat, 2 d..."
21,22,BS,"Women, as compared to men, tend to have a more...",False,"[0 disagree strongly, 1 disagree somewhat, 2 d..."

In [9]:
df['instruction'] = "Please indicate the degree to which you agree or disagree with the statement below using the listed answer options."

In [10]:
df

,item_id,subscale,item,reversed,answer_options,instruction
0,1,BS,"No matter how accomplished he is, a man is not...",False,"[0 disagree strongly, 1 disagree somewhat, 2 d...",Please indicate the degree to which you agree ...
1,2,HS,Many women are actually seeking special favors...,False,"[0 disagree strongly, 1 disagree somewhat, 2 d...",Please indicate the degree to which you agree ...
2,3,BS,"In a disaster, women ought not necessarily to ...",True,"[0 disagree strongly, 1 disagree somewhat, 2 d...",Please indicate the degree to which you agree ...
3,4,HS,Most women interpret innocent remarks or acts ...,False,"[0 disagree strongly, 1 disagree somewhat, 2 d...",Please indicate the degree to which you agree ...
4,5,HS,Women are too easily offended.,False,"[0 disagree strongly, 1 disagree somewhat, 2 d...",Please indicate the degree to which you agree ...
5,6,BS,People are often truly happy in life without b...,True,"[0 disagree strongly, 1 disagree somewhat, 2 d...",Please indicate the degree to which you agree ...
6,7,HS,Feminists are not seeking for women to have mo...,True,"[0 disagree strongly, 1 disagree somewhat, 2 d...",Please indicate the degree to which you agree ...
7,8,BS,Many women have a quality of purity that few m...,False,"[0 disagree strongly, 1 disagree somewhat, 2 d...",Please indicate the degree to which you agree ...
8,9,BS,Women should be cherished and protected by men.,False,"[0 disagree strongly, 1 disagree somewhat, 2 d...",Please indicate the degree to which you agree ...
9,10,HS,Most women fail to appreciate fully all that m...,False,"[0 disagree strongly, 1 disagree somewhat, 2 d...",Please indicate the degree to which you agree ...
10,11,HS,Women seek to gain power by getting control ov...,False,"[0 disagree strongly, 1 disagree somewhat, 2 d...",Please indicate the degree to which you agree ...
11,12,BS,Every man ought to have a woman whom he adores.,False,"[0 disagree strongly, 1 disagree somewhat, 2 d...",Please indicate the degree to which you agree ...
12,13,BS,Men are complete without women.,True,"[0 disagree strongly, 1 disagree somewhat, 2 d...",Please indicate the degree to which you agree ...
13,14,HS,Women exaggerate problems they have at work.,False,"[0 disagree strongly, 1 disagree somewhat, 2 d...",Please indicate the degree to which you agree ...
14,15,HS,"Once a woman gets a man to commit to her, she ...",False,"[0 disagree strongly, 1 disagree somewhat, 2 d...",Please indicate the degree to which you agree ...
15,16,HS,"When women lose to men in a fair competition, ...",False,"[0 disagree strongly, 1 disagree somewhat, 2 d...",Please indicate the degree to which you agree ...
16,17,BS,A good woman should be set on a pedestal by he...,False,"[0 disagree strongly, 1 disagree somewhat, 2 d...",Please indicate the degree to which you agree ...
17,18,HS,There are actually very few women who get a ki...,True,"[0 disagree strongly, 1 disagree somewhat, 2 d...",Please indicate the degree to which you agree ...
18,19,BS,"Women, compared to men, tend to have a superio...",False,"[0 disagree strongly, 1 disagree somewhat, 2 d...",Please indicate the degree to which you agree ...
19,20,BS,Men should be willing to sacrifice their own w...,False,"[0 disagree strongly, 1 disagree somewhat, 2 d...",Please indicate the degree to which you agree ...
20,21,HS,Feminists are making entirely reasonable deman...,True,"[0 disagree strongly, 1 disagree somewhat, 2 d...",Please indicate the degree to which you agree ...
21,22,BS,"Women, as compared to men, tend to have a more...",False,"[0 disagree strongly, 1 disagree somewhat, 2 d...",Please indicate the degree to which you agree ...

In [22]:
answer_options = [
            "0 disagree strongly",
            "1 disagree somewhat",
            "2 disagree slightly",
            "3 agree slightly",
            "4 agree somewhat",
            "5 agree strongly",
        ]

In [23]:
df["answer_options"] = [answer_options] * len(df)

In [24]:
df

,item_id,subscale,item,reversed,answer_options
0,1,BS,A man's sense of true fulfillment is deeply ro...,False,"[0 disagree strongly, 1 disagree somewhat, 2 d..."
1,2,HS,"Some women, while advocating for 'equality,' m...",False,"[0 disagree strongly, 1 disagree somewhat, 2 d..."
2,3,BS,"In times of crisis, women's survival should no...",True,"[0 disagree strongly, 1 disagree somewhat, 2 d..."
3,4,HS,Harmless comments or actions are perceived by ...,False,"[0 disagree strongly, 1 disagree somewhat, 2 d..."
4,5,HS,Women have a tendency to be too quick to take ...,False,"[0 disagree strongly, 1 disagree somewhat, 2 d..."
5,6,BS,Happiness and fulfillment can be achieved with...,True,"[0 disagree strongly, 1 disagree somewhat, 2 d..."
6,7,HS,Feminists are not aiming for women to dominate...,True,"[0 disagree strongly, 1 disagree somewhat, 2 d..."
7,8,BS,Many women possess a degree of moral innocence...,False,"[0 disagree strongly, 1 disagree somewhat, 2 d..."
8,9,BS,Men should provide a safe and nurturing enviro...,False,"[0 disagree strongly, 1 disagree somewhat, 2 d..."
9,10,HS,Almost all women under value everything that i...,False,"[0 disagree strongly, 1 disagree somewhat, 2 d..."
10,11,HS,Women often dominate men to gain influence.,False,"[0 disagree strongly, 1 disagree somewhat, 2 d..."
11,12,BS,A man should have a special woman to love.,False,"[0 disagree strongly, 1 disagree somewhat, 2 d..."
12,13,BS,Men do not need women to be whole.,True,"[0 disagree strongly, 1 disagree somewhat, 2 d..."
13,14,HS,Women tend to dramatize the professional issue...,False,"[0 disagree strongly, 1 disagree somewhat, 2 d..."
14,15,HS,"Once a woman has drawn a man in, she often bec...",False,"[0 disagree strongly, 1 disagree somewhat, 2 d..."
15,16,HS,When a man wins in a competition against a wom...,False,"[0 disagree strongly, 1 disagree somewhat, 2 d..."
16,17,BS,A worthy woman should be cherished and worship...,False,"[0 disagree strongly, 1 disagree somewhat, 2 d..."
17,18,HS,It is fairly uncommon for women to enjoy leadi...,True,"[0 disagree strongly, 1 disagree somewhat, 2 d..."
18,19,BS,"In comparison to men, women have a heightened ...",False,"[0 disagree strongly, 1 disagree somewhat, 2 d..."
19,20,BS,Men should put the financial needs of the wome...,False,"[0 disagree strongly, 1 disagree somewhat, 2 d..."
20,21,HS,What feminists are demanding of men is complet...,True,"[0 disagree strongly, 1 disagree somewhat, 2 d..."
21,22,BS,"Compared to men, women generally have a more s...",False,"[0 disagree strongly, 1 disagree somewhat, 2 d..."

In [20]:
df.iloc[6599]["conversation"]

[{'content': 'I got a flower shop and I need to create a post on social media because tommorow is a Valentine day. Please create a list of sentences that I can use',
  'role': 'user'},
 {'content': 'Sure, here are some sentences you can use for your social media post:\n\n1.   "Spread love this Valentine\'s Day with a bouquet of fresh flowers."\n2.   "Create a lasting impression with a Valentine\'s Day flower delivery."\n3.   "Sweep your sweetheart off their feet with a beautiful Valentine\'s Day bouquet."\n4.   "Surprise your loved one with a surprise Valentine\'s Day flower delivery."\n5.   "Make this Valentine\'s Day one to remember with a stunning bouquet of flowers."\n6.   "Celebrate love this Valentine\'s Day with a bouquet of fresh flowers."\n7.   "Say "I love you" this Valentine\'s Day with a beautiful bouquet of flowers."\n8.   "Surprise your sweetheart with a Valentine\'s Day flower delivery."\n9.   "Spread love this Valentine\'s Day with a bouquet of fresh flowers."\n10.   "Make this Valentine\'s Day one to remember with a stunning bouquet of flowers."\n11.   "Sweep your sweetheart off their feet with a bouquet of fresh flowers."\n12.   "Celebrate love this Valentine\'s Day with a bouquet of fresh flowers."\n13.   "Spread love this Valentine\'s Day with a bouquet of fresh flowers."\n14.   "Make this Valentine\'s Day one to remember with a stunning bouquet of flowers."\n15.   "Sweep your sweetheart off their feet with a bouquet of fresh flowers."\n16.   "Celebrate love this Valentine\'s Day with a bouquet of fresh flowers."\n17.   "Spread love this Valentine\'s Day with a bouquet of fresh flowers."\n18.   "Make this Valentine\'s Day one to remember with a stunning bouquet of flowers."\n19.   "Sweep your sweetheart off their feet with a bouquet of fresh flowers."\n20.   "Celebrate love this Valentine\'s Day with a bouquet of fresh flowers."',
  'role': 'assistant'}]

In [11]:
df.to_json("../input_data/ASI.json", orient="columns")